export const steps = {
  WELCOME: 1,
  CONSENT: 2,
  INSTRUCTIONS: 3,
  TUTORIAL: 4,
  WAITING_ROOM: 5,
  WAITING_ROOM_READY: 6,
  WAITING_ROOM_READY_SUBMITTED: 7,
  DISCUSSION: 8,
  SURVEY_TASK: 9,
  SURVEY_PITH: 10,
  DONE: 11,
  CANCEL: 12,
};
